name: thinking-in-tensors
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - jupyter
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  - h5py

  - pip:
      - seaborn
      - livelossplot
      - openai
